"""Add TasteEvent and RecommendationDecision models

Revision ID: 639b3f696928
Revises: c8e901a1d2f4
Create Date: 2026-08-05 20:00:37.329415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '639b3f696928'
down_revision: Union[str, Sequence[str], None] = 'c8e901a1d2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_request', sa.Text(), nullable=False),
    sa.Column('parsed_intent', sqlite.JSON(), nullable=True),
    sa.Column('candidates', sqlite.JSON(), nullable=True),
    sa.Column('ranked_result', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('taste_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('profile_before', sqlite.JSON(), nullable=True),
    sa.Column('profile_after', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taste_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taste_events_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taste_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_taste_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crunchiness_preference', sa.Float(), nullable=True))
        batch_op.drop_column('crunch_preference')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crunch_preference', sa.FLOAT(), nullable=True))
        batch_op.drop_column('crunchiness_preference')

    with op.batch_alter_table('taste_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taste_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_taste_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_taste_events_dish_id'))

    op.drop_table('taste_events')
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_user_id'))

    op.drop_table('recommendation_decisions')
    # ### end Alembic commands ###
