"""sync_missing_columns

Revision ID: d0964ab087e6
Revises: 639b3f696928
Create Date: 2026-08-05 22:02:14.952111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd0964ab087e6'
down_revision: Union[str, Sequence[str], None] = '639b3f696928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dietary_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_aliases_ingredient_id'), ['ingredient_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('community_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('would_reorder', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_signals_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_signals_user_id'), ['user_id'], unique=False)

    op.create_table('dish_allergens',
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('allergen_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'allergen_id')
    )
    op.create_table('dish_dietary_tags',
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['dietary_tags.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'tag_id')
    )
    op.create_table('dish_ingredients',
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    op.create_table('dish_pairings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('paired_dish_id', sa.String(), nullable=False),
    sa.Column('pairing_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['paired_dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dish_pairings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_pairings_dish_id'), ['dish_id'], unique=False)

    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=False),
    sa.Column('vector_dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_embeddings_chunk_id'), ['chunk_id'], unique=True)

    op.create_table('restaurant_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('chef_notes', sa.Text(), nullable=True),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('spice_calibration', sa.Text(), nullable=True),
    sa.Column('customization_options', sa.Text(), nullable=True),
    sa.Column('known_substitutions', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_notes_dish_id'), ['dish_id'], unique=True)

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spice_level', sa.Numeric(precision=4, scale=3), nullable=True))
        batch_op.add_column(sa.Column('sweetness_level', sa.Numeric(precision=4, scale=3), nullable=True))
        batch_op.add_column(sa.Column('creaminess_level', sa.Numeric(precision=4, scale=3), nullable=True))
        batch_op.add_column(sa.Column('tanginess_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('masala_intensity_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crunchiness_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('allergens', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dietary_tags', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recommended_pairings', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preparation_style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('chef_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('serving_style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recommended_temperature', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('popularity_score', sa.Numeric(precision=4, scale=3), nullable=True))
        batch_op.alter_column('oiliness_level',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'"))
        batch_op.alter_column('saltiness_level',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'"))
        batch_op.drop_column('masala_intensity')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hero_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_restaurants_slug'), ['slug'], unique=True)

    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dna_matrix_json', sqlite.JSON(), nullable=True))
        batch_op.drop_column('smokiness_preference')
        batch_op.drop_column('adventure_level')
        batch_op.drop_column('portion_preference')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion_preference', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('adventure_level', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('smokiness_preference', sa.FLOAT(), nullable=True))
        batch_op.drop_column('dna_matrix_json')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_slug'))
        batch_op.drop_column('price_range')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('city')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('hero_image')
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('logo')
        batch_op.drop_column('slug')

    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masala_intensity', sa.NUMERIC(precision=4, scale=3), server_default=sa.text("'0.5'"), nullable=True))
        batch_op.alter_column('saltiness_level',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'"))
        batch_op.alter_column('oiliness_level',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'"))
        batch_op.drop_column('popularity_score')
        batch_op.drop_column('recommended_temperature')
        batch_op.drop_column('serving_style')
        batch_op.drop_column('chef_notes')
        batch_op.drop_column('preparation_style')
        batch_op.drop_column('recommended_pairings')
        batch_op.drop_column('dietary_tags')
        batch_op.drop_column('allergens')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('crunchiness_level')
        batch_op.drop_column('masala_intensity_level')
        batch_op.drop_column('tanginess_level')
        batch_op.drop_column('creaminess_level')
        batch_op.drop_column('sweetness_level')
        batch_op.drop_column('spice_level')

    with op.batch_alter_table('restaurant_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_notes_dish_id'))

    op.drop_table('restaurant_notes')
    with op.batch_alter_table('knowledge_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_embeddings_chunk_id'))

    op.drop_table('knowledge_embeddings')
    with op.batch_alter_table('dish_pairings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_pairings_dish_id'))

    op.drop_table('dish_pairings')
    op.drop_table('dish_ingredients')
    op.drop_table('dish_dietary_tags')
    op.drop_table('dish_allergens')
    with op.batch_alter_table('community_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_signals_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_signals_dish_id'))

    op.drop_table('community_signals')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_restaurant_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('ingredient_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_aliases_ingredient_id'))

    op.drop_table('ingredient_aliases')
    op.drop_table('ingredients')
    op.drop_table('dietary_tags')
    op.drop_table('allergens')
    # ### end Alembic commands ###
